### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by Nico-Amplexor** [oxygenxml/dita-merged#1]
Hello,

The plugin folder is called "com.oxygenxml.merged" but in plugin.xml we have "plugin id="com.oxygenxml.merge"". 
A "d" is missing.

So, if you want to use ${dita.plugin.com.oxygenxml.merged.dir} variable it doesn't works.

**Comment by raducoravu** [comment]
Thanks, I modified the ID in the plugin.xml
